# Generated by Django 4.1.2 on 2023-11-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('normal', 'normal'), ('subscriber', 'subscriber'), ('moderator', 'moderator')], default='regular', max_length=100),
        ),
    ]
