# Generated by Django 4.1.2 on 2023-12-01 21:09

from django.db import migrations, models
import django.db.models.deletion
import urun.models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0002_filtre'),
    ]

    operations = [
        migrations.CreateModel(
            name='filtre_icerigi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtre_adi', urun.models.user_adi(max_length=100, verbose_name='Filtre Adı Türkçe')),
                ('filtre_bagli_oldu_filtre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urun.filtre', verbose_name=' Kategori Bilgisi')),
            ],
        ),
    ]
