# Generated by Django 4.1.2 on 2023-12-07 12:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0003_filtre_icerigi'),
    ]

    operations = [
        migrations.CreateModel(
            name='urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ürün Adı')),
                ('fiyat', models.FloatField(blank=True, null=True, verbose_name='Fiyat Bilgisi')),
                ('urun_aciklama', ckeditor.fields.RichTextField(verbose_name='Ürün Açıklama')),
                ('kategori', models.ManyToManyField(blank=True, null=True, to='urun.meslek')),
            ],
        ),
    ]
