# Generated by Django 4.1.2 on 2023-12-08 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0004_urun'),
    ]

    operations = [
        migrations.CreateModel(
            name='urun_resimleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='gallery/')),
                ('urun_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urun.urun', verbose_name='Ürün Bilgisi')),
            ],
        ),
    ]
