# Generated by Django 4.1.2 on 2023-12-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0006_urun_urun_stok'),
    ]

    operations = [
        migrations.AddField(
            model_name='meslek',
            name='silinme_bilgisi',
            field=models.BooleanField(default=False, verbose_name='Silinme Bilgisi'),
        ),
    ]
