# Generated by Django 4.1.2 on 2023-12-09 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0008_filtre_silinme_bilgisi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='urun_filtre_tercihi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtre_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urun.filtre_icerigi', verbose_name='Filtre İçeriğini Seç')),
                ('urun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urun.urun', verbose_name='Ürün Bilgisi')),
            ],
        ),
    ]
