# Generated by Django 4.1.2 on 2023-12-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0009_urun_filtre_tercihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtre_icerigi',
            name='filtre_renk_kodu',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Renk Eklemek ilsterseniz'),
        ),
    ]
