# Generated by Django 4.1.2 on 2023-12-10 12:39

from django.db import migrations
import urun.models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0011_urun_urun_bakma_saysi'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtre_icerigi',
            name='filtre_linki',
            field=urun.models.kategory_link_ayari(blank=True, max_length=200, null=True, verbose_name='Filtre Linki'),
        ),
    ]
