# Generated by Django 4.1.2 on 2023-12-10 12:41

from django.db import migrations
import urun.models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0012_filtre_icerigi_filtre_linki'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtre_icerigi',
            name='filtre_linki',
        ),
        migrations.AddField(
            model_name='filtre',
            name='filtre_linki',
            field=urun.models.kategory_link_ayari(blank=True, max_length=200, null=True, verbose_name='Filtre Linki'),
        ),
    ]
