# Generated by Django 4.1.2 on 2023-12-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0013_remove_filtre_icerigi_filtre_linki_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urun_resimleri',
            old_name='images',
            new_name='image',
        ),
    ]
