# Generated by Django 4.1.2 on 2023-12-18 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0015_ip_sepet_olusturma'),
    ]

    operations = [
        migrations.CreateModel(
            name='sepetteki_urunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kayitli_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urun.sepet_olusturma')),
                ('kayitli_olmayan_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urun.ip')),
                ('urun_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urun.urun')),
            ],
        ),
    ]
