# Generated by Django 4.1.2 on 2023-12-18 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0016_sepetteki_urunler'),
    ]

    operations = [
        migrations.CreateModel(
            name='sepet_olusturma_ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepet_satin_alma_durumu', models.BooleanField(default=False)),
                ('sepet_sahibi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urun.ip')),
            ],
        ),
        migrations.AlterField(
            model_name='sepetteki_urunler',
            name='kayitli_olmayan_kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urun.sepet_olusturma_ip'),
        ),
    ]
