# Generated by Django 4.1.2 on 2023-12-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0018_alter_sepet_olusturma_ip_sepet_sahibi_delete_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepetteki_urunler',
            name='urun_adedi',
            field=models.BigIntegerField(default=1, verbose_name='ürün Adedi'),
        ),
    ]
