# Generated by Django 4.1.2 on 2024-01-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0019_sepetteki_urunler_urun_adedi'),
    ]

    operations = [
        migrations.CreateModel(
            name='sepet_sahibi_bilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=200, null=True, verbose_name='İsim ')),
                ('soyisim', models.CharField(blank=True, max_length=200, null=True, verbose_name='Soysisim ')),
                ('vergi_tc', models.CharField(blank=True, max_length=200, null=True, verbose_name='vergi_tc ')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='email ')),
                ('telefon', models.CharField(blank=True, max_length=200, null=True, verbose_name='telefon ')),
                ('adres', models.TextField(blank=True, null=True, verbose_name='ADres')),
                ('ulke', models.CharField(blank=True, max_length=200, null=True, verbose_name='ulke ')),
                ('sehirler', models.CharField(blank=True, max_length=200, null=True, verbose_name='sehirler ')),
                ('zip_kodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Zip_kodu ')),
                ('payment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ödeme Şekli')),
                ('kayitli_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urun.sepet_olusturma')),
                ('kayitli_olmayan_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urun.sepet_olusturma_ip')),
            ],
        ),
    ]
