# Generated by Django 4.1.2 on 2024-01-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0020_sepet_sahibi_bilgileri'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepet_sahibi_bilgileri',
            name='faturatipi',
            field=models.BooleanField(default=False, verbose_name='False İse Bireyseldir'),
        ),
    ]
