# Generated by Django 4.1.2 on 2024-01-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0022_satin_alinanlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='satin_alinanlar',
            name='kargo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kargo Takip Numarası'),
        ),
        migrations.AddField(
            model_name='satin_alinanlar',
            name='kargo_sirketi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kargo Şirketi'),
        ),
    ]
