# Generated by Django 4.1.2 on 2024-01-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0023_satin_alinanlar_kargo_satin_alinanlar_kargo_sirketi'),
    ]

    operations = [
        migrations.AddField(
            model_name='satin_alinanlar',
            name='siparis_numarasi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kargo Takip Numarası'),
        ),
    ]
