# Generated by Django 4.1.2 on 2024-01-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0024_satin_alinanlar_siparis_numarasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='banka_bilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banka', models.CharField(blank=True, max_length=200, null=True, verbose_name='Banka Adı')),
                ('isim_soyisim', models.CharField(blank=True, max_length=400, null=True, verbose_name='Adı Soyadı')),
                ('iban', models.CharField(blank=True, max_length=200, null=True, verbose_name='iban')),
            ],
        ),
    ]
