# Generated by Django 4.1.2 on 2024-01-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0025_banka_bilgileri'),
    ]

    operations = [
        migrations.AddField(
            model_name='meslek',
            name='numarasi',
            field=models.IntegerField(default=0, verbose_name='sıralaması'),
        ),
    ]
