# Generated by Django 4.1.2 on 2024-01-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urun", "0026_meslek_numarasi"),
    ]

    operations = [
        migrations.AddField(
            model_name="urun",
            name="partikodu",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="ürün partikodu"
            ),
        ),
    ]
