# Generated by Django 4.1.2 on 2024-01-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0027_urun_partikodu'),
    ]

    operations = [
        migrations.AddField(
            model_name='meslek',
            name='headerda_gosterme',
            field=models.BooleanField(default=False, verbose_name='headerda Görünsün'),
        ),
    ]
