# Generated by Django 4.1.2 on 2024-01-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0028_meslek_headerda_gosterme'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='eski_fiyat',
            field=models.FloatField(blank=True, null=True, verbose_name='Fiyat Bilgisi'),
        ),
    ]
