# Generated by Django 4.1.2 on 2024-01-28 14:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0029_urun_eski_fiyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='urun_aciklama',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ürün Açıklama'),
        ),
    ]
