# Generated by Django 4.1.2 on 2024-02-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0030_alter_urun_urun_aciklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='satin_alinanlar',
            name='tutar',
            field=models.FloatField(default=0, verbose_name='Tutar'),
        ),
        migrations.AlterField(
            model_name='filtre_icerigi',
            name='filtre_renk_kodu',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Filtre Açıklaması '),
        ),
    ]
