# Generated by Django 4.1.2 on 2024-02-18 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0031_satin_alinanlar_tutar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtre_icerigi',
            name='filtre_renk_kodu',
        ),
    ]
