# Generated by Django 4.1.2 on 2024-02-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0032_remove_filtre_icerigi_filtre_renk_kodu'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
