# Generated by Django 3.2.18 on 2024-07-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0034_filtre_icerigi_filtre_renk_kodu'),
    ]

    operations = [
        migrations.AddField(
            model_name='meslek',
            name='image',
            field=models.ImageField(default=0, upload_to='gallery/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meslek',
            name='slaytta_gorunsun',
            field=models.BooleanField(default=False, verbose_name='Slaytta Görünme Bilgisi'),
        ),
    ]
