# Generated by Django 4.1.2 on 2023-12-07 11:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket_adresi_tr', models.CharField(max_length=200, verbose_name='Şirket Adresi Türkçe')),
            ],
        ),
        migrations.CreateModel(
            name='anasayfa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hakkimizda_tr', ckeditor.fields.RichTextField(verbose_name='Anasayfa Yazısı Türkçe')),
            ],
        ),
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_basligi_tr', models.CharField(max_length=400, verbose_name='Banner Başliği Türkçe')),
                ('banner_aciklama_tr', models.TextField(max_length=400, verbose_name='Banner Aciklama Türkçe')),
                ('banner_sira', models.IntegerField(verbose_name='Banner Gösterme Sırası')),
                ('banner_gosterme', models.BooleanField(verbose_name='Banner Gösterilsin mi ? ')),
                ('banner_link', models.CharField(blank=True, max_length=400, null=True, verbose_name='Bannera Link Brakmak İstiyorsanız link Ekleyin')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Sayfaya Banner Ekleyin')),
            ],
        ),
        migrations.CreateModel(
            name='email_adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket_email_adresi', models.EmailField(max_length=200, verbose_name='Şirket Email Adresi')),
            ],
        ),
        migrations.CreateModel(
            name='gomulu_adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket_adresi_tr', models.CharField(max_length=1000, verbose_name='Şirket Adresi Türkçe')),
            ],
        ),
        migrations.CreateModel(
            name='hakkimizda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hakkimizda_tr', ckeditor.fields.RichTextField(verbose_name='Hakkımızda Yazısı Türkçe')),
            ],
        ),
        migrations.CreateModel(
            name='numara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket_numarasi_gosterilecek_metin', models.CharField(max_length=20, verbose_name='Telefon Sitede Nasıl görünecek')),
                ('sirket_numarasi', models.CharField(max_length=20, verbose_name='Aranacak Numara Başında + olmadan ülke kodu ile Yazabilirisniz')),
            ],
        ),
        migrations.CreateModel(
            name='sayfa_iconu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sayfa_icon', models.FileField(upload_to='logo/', verbose_name='Sayfaya ikon ekleyin')),
            ],
        ),
        migrations.CreateModel(
            name='sayfa_logosu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logo/', verbose_name='Sayfaya Logo Ekleyin')),
            ],
        ),
        migrations.CreateModel(
            name='seo_ayarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_seo_kelimeleri_tr', models.TextField(max_length=400, verbose_name='Seo Kelmeleri Türkçe')),
                ('site_seo_metni_tr', models.TextField(max_length=400, verbose_name='Seo Metni Türkçe')),
            ],
        ),
        migrations.CreateModel(
            name='site_adi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_adi_genel', models.CharField(max_length=200, verbose_name='Google Nasıl Görünecek')),
                ('site_adi_sekme_tr', models.CharField(max_length=200, verbose_name='Sekmede Görünme Türkçe')),
            ],
        ),
        migrations.CreateModel(
            name='sosyalmedyaFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400, verbose_name='Şirket Facebook Linki')),
            ],
        ),
        migrations.CreateModel(
            name='sosyalmedyaInsgr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400, verbose_name='Şirket İnstagram Linki')),
            ],
        ),
        migrations.CreateModel(
            name='sosyalmedyalinkd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400, verbose_name='Şirket Linkedin Linki')),
            ],
        ),
        migrations.CreateModel(
            name='sosyalmedyatw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400, verbose_name='Şirket TW Linki')),
            ],
        ),
        migrations.CreateModel(
            name='sosyalmedyayoutube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400, verbose_name='Şirket Youtube Linki')),
            ],
        ),
    ]
