# Generated by Django 4.1.2 on 2024-01-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='odeme_ayarlari_paytr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magaza_adi', models.CharField(max_length=200, verbose_name='Mağaza Adı')),
                ('magaza_parolasi', models.CharField(max_length=400, verbose_name='Mağaza Parolası')),
                ('magaza_gizli_anahtar', models.CharField(max_length=400, verbose_name='Mağaza Gizli Anahtar')),
            ],
        ),
    ]
