# Generated by Django 4.1.2 on 2024-01-08 17:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0002_odeme_ayarlari_paytr'),
    ]

    operations = [
        migrations.CreateModel(
            name='yasal_metinler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yasal_metin_basligi', models.CharField(max_length=200, verbose_name='yasal Metin Başlığı')),
                ('yasalmetin', ckeditor.fields.RichTextField(verbose_name='Anasayfa Yazısı Türkçe')),
            ],
        ),
    ]
