# Generated by Django 3.2.18 on 2024-07-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0005_kargo_tutari'),
    ]

    operations = [
        migrations.CreateModel(
            name='sitefooteryazisiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_footer_yazisi', models.CharField(max_length=400, verbose_name='site Footer Yazısı')),
            ],
        ),
    ]
